name: Deploy to Railway

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.com/install.sh | sh

      - name: Deploy to Railway
        run: railway up -d -s fintech-backend -p 81dc46f1-1710-4015-9dd1-eab90c1a6db9 -e production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
